sudo: required
services:
  - docker

before_install:
  - docker build -t test -f Dockerfile.dev .

script:
  - docker run test npm test -- --coverage

after_success:
  - docker build -t yaf20030918/ampos .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push yaf20030918/ampos